---
# name: '{{ ansible_name_module }} | command:skopeo.copy | Pull CloudCTL Pod Images' 
# file: 
#   path: "{{ dir_deploy }}/images"
#   state: directory

- name: '{{ ansible_name_module }} | command:skopeo.copy | Pull App Images' 
  command:
    argv:
      - skopeo
      - copy
      - 'docker://{{ item.url }}/{{ item.name }}'
      - 'docker://localhost:5000/{{ item.name }}'
  loop:
    - { url: '{{ url_registry_k8s }}', name: '{{ images_apps_k8s }}' }
