---
# name: '{{ ansible_name_module }} | command:skopeo.copy | Pull CloudCTL Pod Images' 
# file: 
#   path: "{{ dir_deploy }}/images"
#   state: directory

- name: '{{ ansible_name_module }} | command:skopeo.copy | Pull App Images' 
  command:
    argv:
      - skopeo
      - copy
      - 'docker://{{ url_registry_k8s }}/{{ item.name }}'
      - 'docker://localhost:5000/{{ item.name }}'
  with_items:
    - '{{ images_apps_k8s }}'
