---
# name: '{{ ansible_name_module }} | command:skopeo.copy | Pull CloudCTL Pod Images' 
# file: 
#   path: "{{ dir_deploy }}/images"
#   state: directory

- name: '{{ ansible_name_module }} | command:skopeo.copy | {{ url_registry_quay }} | Pull App Images' 
  command:
    argv:
      - skopeo
      - copy
      - 'docker://{{ url_registry_quay }}/{{ item }}'
      - 'docker://localhost:5000/{{ item }}'
  with_items:
    - '{{ images_apps_quay }}'

- name: '{{ ansible_name_module }} | command:skopeo.copy | {{ url_registry_docker }} | Pull App Images' 
  command:
    argv:
      - skopeo
      - copy
      - 'docker://{{ url_registry_docker }}/{{ item }}'
      - 'docker://localhost:5000/{{ item }}'
  with_items:
    - '{{ images_apps_docker }}'
  ignore_errors: true

- name: '{{ ansible_name_module }} | command:skopeo.copy | {{ url_registry_k8s }} | Pull App Images' 
  command:
    argv:
      - skopeo
      - copy
      - 'docker://{{ url_registry_k8s }}/{{ item }}'
      - 'docker://localhost:5000/{{ item }}'
  with_items:
    - '{{ images_apps_k8s }}'

